build_from: 
  amd64: "ghcr.io/home-assistant/amd64-base-debian:bookworm"
  aarch64: "ghcr.io/home-assistant/aarch64-base-debian:bookworm"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: ptbsare add-on"
  org.opencontainers.image.description: "Wyoming integration for sherpa-onnx TTS and STT."
  org.opencontainers.image.source: "https://github.com/ptbsare/home-assistant-addons"
  org.opencontainers.image.licenses: "MIT"
